# ==========================================
# HYPRLOCK TTY / EMPTTY RETRO CONFIG
# ==========================================

general{
    hide_cursor = true
}

animations{
    enabled = false
    animation = fade, 0, 0, default
    animation = fadeOut, 0, 0, default
    animation = inputFieldDots, 0, 0, default
}

background{
    monitor = 
    # path = /home/atlas/dotfiles/wallpapers/
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0    
}

# The Interactive Password Input Box disguised as a TTY prompt
input-field {
    monitor = 
    size = 300, 30
    outline_thickness = 0          
    dots_size = 0.8               
    dots_spacing = 0.1 
    dots_center = true

    dots_text_format = *
    
    font_color = rgb(200, 200, 200)
    font_family = JetBrains Mono
    
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    
    # --- FIXED STATE COLORS ---
    check_color = rgba(0, 0, 0, 0)      # Stop the green validation flash
    fail_color = rgb(200, 200, 200)    # Stop the red failure flash (forces gray)
    bothlock_color = rgb(200, 200, 200) # Stop any caps/num lock alert colors
    
    position = 0, -150           
    halign = center
    valign = center
}

