wallpaper {
    monitor = eDP-1
    # path = ~/wallpapers/ashipinwater.jpg
    path = ~/wallpapers/asusgram.png
    fit_mode = cover
}
wallpaper {
    monitor = eDP-2
    # path = ~/wallpapers/ashipinwater.jpg
    path = ~/wallpapers/asusgram.png
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    # path = ~/wallpapers/ashipinwater.jpg
    path = ~/wallpapers/asusgram.png
    fit_mode = cover
}

splash = false

# ipc = off
