ipc = on

wallpaper {
    monitor = eDP-1
    path = ~/dotfiles/wallpapers/activeWallpaper
    fit_mode = cover
}
wallpaper {
    monitor = eDP-2
    path = ~/dotfiles/wallpapers/activeWallpaper
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = ~/dotfiles/wallpapers/activeWallpaper
    fit_mode = cover
}

splash = false
